spring.application.name=notes_service

spring.datasource.url=jdbc:mysql://localhost:3306/notestaking
spring.datasource.username=root
spring.datasource.password=87690
spring.security.user.name=admin
spring.security.user.password=your_secure_password


# to get automatically create tables by detecting @Entity annotation
spring.jpa.hibernate.ddl-auto=update

#to pring sql queries to our application console
spring.jpa.show-sql=true

#to see queries in more readable way
spring.jpa.properties.hibernate.format_sql=true


