spring.application.name=notes_service

#Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/notestaking
spring.datasource.username=${DATABASE_NAME}
spring.datasource.password=${DATABASE_PASSWORD}
# to get automatically create tables by detecting @Entity annotation
spring.jpa.hibernate.ddl-auto=update

#to pring sql queries to our application console
spring.jpa.show-sql=true

#to see queries in more readable way
spring.jpa.properties.hibernate.format_sql=true


#Google OAuth client
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=profile,email

#Google OAuth Provider
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true